name: Notebook CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-notebook:
    runs-on: ubuntu-latest  # CI runs in cloud, OS-independent

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Execute notebook
      run: jupyter nbconvert --to notebook --execute YourNotebook.ipynb --output executed_notebook.ipynb

    - name: Convert notebook to HTML
      run: jupyter nbconvert --to html executed_notebook.ipynb

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v3
      with:
        name: executed-notebook-html
        path: executed_notebook.html
